// src/views/components/element/TextElement/index.vue
<template>
  <div 
    class="editable-element-text" 
    :style="{
      top: elementInfo.top + 'px',
      left: elementInfo.left + 'px',
      width: elementInfo.width + 'px',
      height: elementInfo.height + 'px',
    }"
  >
    <div
      class="rotate-wrapper"
      :style="{ transform: `rotate(${elementInfo.rotate}deg)` }"
    >
      <div 
        class="element-content"
        ref="elementRef"
        :style="{
          width: elementInfo.vertical ? 'auto' : elementInfo.width + 'px',
          height: elementInfo.vertical ? elementInfo.height + 'px' : 'auto',
          backgroundColor: elementInfo.fill,
          opacity: elementInfo.opacity,
          textShadow: shadowStyle,
          lineHeight: elementInfo.lineHeight,
          letterSpacing: (elementInfo.wordSpace || 0) + 'px',
          color: elementInfo.defaultColor,
          fontFamily: elementInfo.defaultFontName,
          writingMode: elementInfo.vertical ? 'vertical-rl' : 'horizontal-tb',
        }"
        v-contextmenu="contextmenus"
        @mousedown="$event => handleSelectElement($event)"
        @touchstart="$event => handleSelectElement($event)"
      >
        <ElementOutline
          :width="elementInfo.width"
          :height="elementInfo.height"
          :outline="elementInfo.outline"
        />
        <ProsemirrorEditor
          class="text"
          :elementId="elementInfo.id"
          :defaultColor="elementInfo.defaultColor"
          :defaultFontName="elementInfo.defaultFontName"
          :editable="true"
          :value="elementInfo.content"
          :style="{
            '--paragraphSpace': `${elementInfo.paragraphSpace === undefined ? 5 : elementInfo.paragraphSpace}px`,
          }"
          @update="({ value, ignore }) => updateContent(value, ignore)"
          @mousedown="$event => handleSelectElement($event, false)"
        />

        <!-- 当字号过大且行高较小时，会出现文字高度溢出的情况，导致拖拽区域无法被选中，因此添加了以下节点避免该情况 -->
        <div class="drag-handler top"></div>
        <div class="drag-handler bottom"></div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed, onMounted, onUnmounted, ref, watch, useTemplateRef } from 'vue'
import { storeToRefs } from 'pinia'
import { debounce } from 'lodash'
import { useMainStore, useSlidesStore } from '@/store'
import type { PPTTextElement } from '@/types/slides'
import type { ContextmenuItem } from '@/components/Contextmenu/types'
import useElementShadow from '@/views/components/element/hooks/useElementShadow'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'

import ElementOutline from '@/views/components/element/ElementOutline.vue'
import ProsemirrorEditor from '@/views/components/element/ProsemirrorEditor.vue'

const props = defineProps<{
  elementInfo: PPTTextElement
  selectElement: (e: MouseEvent | TouchEvent, element: PPTTextElement, canMove?: boolean) => void
  contextmenus: () => ContextmenuItem[] | null
}>()

const mainStore = useMainStore()
const slidesStore = useSlidesStore()
const { handleElementId, isScaling } = storeToRefs(mainStore)

const { addHistorySnapshot } = useHistorySnapshot()

const elementRef = useTemplateRef<HTMLElement>('elementRef')

const shadow = computed(() => props.elementInfo.shadow)
const { shadowStyle } = useElementShadow(shadow)

/**
 * 处理元素选择事件
 * @param e 鼠标或触摸事件
 * @param canMove 是否允许移动
 */
const handleSelectElement = (e: MouseEvent | TouchEvent, canMove = true) => {
  e.stopPropagation()

  props.selectElement(e, props.elementInfo, canMove)
}

// 监听文本元素的尺寸变化，当高度变化时，更新高度到vuex
// 如果高度变化时正处在缩放操作中，则等待缩放操作结束后再更新
const realHeightCache = ref(-1)
const realWidthCache = ref(-1)

watch(isScaling, () => {
  if (handleElementId.value !== props.elementInfo.id) return

  if (!isScaling.value) {
    if (!props.elementInfo.vertical && realHeightCache.value !== -1) {
      slidesStore.updateElement({
        id: props.elementInfo.id,
        props: { height: realHeightCache.value },
      })
      realHeightCache.value = -1
    }
    if (props.elementInfo.vertical && realWidthCache.value !== -1) {
      slidesStore.updateElement({
        id: props.elementInfo.id,
        props: { width: realWidthCache.value },
      })
      realWidthCache.value = -1
    }
  }
})

const updateTextElementHeight = (entries: ResizeObserverEntry[]) => {
  const contentRect = entries[0].contentRect
  if (!elementRef.value) return

  const realHeight = contentRect.height + 20
  const realWidth = contentRect.width + 20

  if (!props.elementInfo.vertical && props.elementInfo.height !== realHeight) {
    if (!isScaling.value) {
      slidesStore.updateElement({
        id: props.elementInfo.id,
        props: { height: realHeight },
      })
    }
    else realHeightCache.value = realHeight
  }
  if (props.elementInfo.vertical && props.elementInfo.width !== realWidth) {
    if (!isScaling.value) {
      slidesStore.updateElement({
        id: props.elementInfo.id,
        props: { width: realWidth },
      })
    }
    else realWidthCache.value = realWidth
  }
}
const resizeObserver = new ResizeObserver(updateTextElementHeight)

onMounted(() => {
  if (elementRef.value) resizeObserver.observe(elementRef.value)
})
onUnmounted(() => {
  if (elementRef.value) resizeObserver.unobserve(elementRef.value)
})

const updateContent = (content: string, ignore = false) => {
  slidesStore.updateElement({
    id: props.elementInfo.id,
    props: { content },
  })
  
  if (!ignore) addHistorySnapshot()
}

const checkEmptyText = debounce(function() {
  const pureText = props.elementInfo.content.replace(/<[^>]+>/g, '')
  if (!pureText) slidesStore.deleteElement(props.elementInfo.id)
}, 300, { trailing: true })

const isHandleElement = computed(() => handleElementId.value === props.elementInfo.id)
watch(isHandleElement, () => {
  if (!isHandleElement.value) checkEmptyText()
})
</script>

<style lang="scss" scoped>
.editable-element-text {
  position: absolute;
}
.rotate-wrapper {
  width: 100%;
  height: 100%;
}
.element-content {
  position: relative;
  padding: 10px;
  line-height: 1.5;
  word-break: break-word;
  cursor: move;

  .text {
    position: relative;
  }

  ::v-deep(a) {
    cursor: text;
  }
}
.drag-handler {
  height: 10px;
  position: absolute;
  left: 0;
  right: 0;

  &.top {
    top: 0;
  }
  &.bottom {
    bottom: 0;
  }
}
</style>

// src/views/components/element/TextElement/index.tsx
import React, {
  useRef,
  useEffect,
  useState,
  useCallback,
  useMemo,
} from 'react'
import { debounce } from 'lodash'
import { useMainStore, useSlidesStore } from '@/store'
import type { PPTTextElement } from '@/types/slides'
import useElementShadow from '@/views/components/element/hooks/useElementShadow'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'

import ElementOutline from '@/views/components/element/ElementOutline'
import ProsemirrorEditor from '@/views/components/element/ProsemirrorEditor'
import './index.scss'
import type { ContextmenuItem } from '@/components/Contextmenu/types'
import useContextMenu from '@/hooks/useContextMenu'

export interface ElementProps {
  elementInfo: PPTTextElement;
  selectElement: (
    e: MouseEvent | TouchEvent,
    element: PPTTextElement,
    canMove?: boolean
  ) => void;
  contextmenus: () => ContextmenuItem[] | null;
}

const TextElement: React.FC<ElementProps> = ({
  elementInfo,
  selectElement,
  contextmenus,
}) => {
  const element = elementInfo as PPTTextElement
  const { handleElementId, isScaling } = useMainStore()
  const { updateElement, deleteElement } = useSlidesStore()
  const { addHistorySnapshot } = useHistorySnapshot()

  const elementRef = useRef<HTMLDivElement>(null)

  const { shadowStyle } = useElementShadow(element.shadow)

  const handleSelectElement = (
    e: React.MouseEvent | React.TouchEvent,
    canMove = true
  ) => {
    e.stopPropagation()
    selectElement?.(e.nativeEvent, element, canMove)
  }

  // 监听文本元素的尺寸变化
  const realHeightCache = useRef(-1)
  const realWidthCache = useRef(-1)

  useEffect(() => {
    if (!isScaling && handleElementId === element.id) {
      if (!element.vertical && realHeightCache.current !== -1) {
        updateElement({
          id: element.id,
          props: { height: realHeightCache.current },
        })
        realHeightCache.current = -1
      }
      if (element.vertical && realWidthCache.current !== -1) {
        updateElement({
          id: element.id,
          props: { width: realWidthCache.current },
        })
        realWidthCache.current = -1
      }
    }
  }, [isScaling, handleElementId, element.id, element.vertical, updateElement])

  const updateTextElementHeight = useCallback(
    (entries: ResizeObserverEntry[]) => {
      const contentRect = entries[0].contentRect
      if (!elementRef.current) return

      const realHeight = contentRect.height + 20
      const realWidth = contentRect.width + 20

      if (!element.vertical && element.height !== realHeight) {
        if (!isScaling) {
          updateElement({
            id: element.id,
            props: { height: realHeight },
          })
        }
        else realHeightCache.current = realHeight
      }
      if (element.vertical && element.width !== realWidth) {
        if (!isScaling) {
          updateElement({
            id: element.id,
            props: { width: realWidth },
          })
        }
        else realWidthCache.current = realWidth
      }
    },
    [
      element.vertical,
      element.height,
      element.width,
      element.id,
      isScaling,
      updateElement,
    ]
  )

  useEffect(() => {
    const resizeObserver = new ResizeObserver(updateTextElementHeight)
    if (elementRef.current) resizeObserver.observe(elementRef.current)
    return () => {
      if (elementRef.current) resizeObserver.unobserve(elementRef.current)
      resizeObserver.disconnect()
    }
  }, [updateTextElementHeight])

  const updateContent = (value: string, ignore = false) => {
    updateElement({
      id: element.id,
      props: { content: value },
    })

    if (!ignore) addHistorySnapshot()
  }

  const checkEmptyText = useMemo(
    () =>
      debounce(
        () => {
          const pureText = element.content.replace(/<[^>]+>/g, '')
          if (!pureText) deleteElement(element.id)
        },
        300,
        { trailing: true }
      ),
    [element.content, element.id, deleteElement]
  )

  const isHandleElement = handleElementId === element.id

  useEffect(() => {
    if (!isHandleElement) {
      checkEmptyText()
    }
  }, [isHandleElement])

  /**
   * 绑定右键菜单到内容容器
   */
  useContextMenu(elementRef, () => contextmenus?.() || [])

  return (
    <div
      className="editable-element-text"
      style={{
        top: element.top + 'px',
        left: element.left + 'px',
        width: element.width + 'px',
        height: element.height + 'px',
      }}
    >
      <div
        className="rotate-wrapper"
        style={{ transform: `rotate(${element.rotate}deg)` }}
      >
        <div
          className="element-content"
          ref={elementRef}
          style={{
            width: element.vertical ? 'auto' : element.width + 'px',
            height: element.vertical ? element.height + 'px' : 'auto',
            backgroundColor: element.fill,
            opacity: element.opacity,
            textShadow: shadowStyle,
            lineHeight: element.lineHeight,
            letterSpacing: (element.wordSpace || 0) + 'px',
            color: element.defaultColor,
            fontFamily: element.defaultFontName,
            writingMode: element.vertical ? 'vertical-rl' : 'horizontal-tb',
          }}
          onMouseDown={(e) => handleSelectElement(e)}
          onTouchStart={(e) => handleSelectElement(e)}
        >
          <ElementOutline
            width={element.width}
            height={element.height}
            outline={element.outline}
          />
          <ProsemirrorEditor
            className="text"
            elementId={element.id}
            defaultColor={element.defaultColor}
            defaultFontName={element.defaultFontName}
            editable={true}
            value={element.content}
            style={
              {
                '--paragraphSpace': `${
                  element.paragraphSpace === undefined
                    ? 5
                    : element.paragraphSpace
                }px`,
              } as React.CSSProperties
            }
            onUpdate={({ value, ignore }) => updateContent(value, ignore)}
            onMouseDown={(e) => handleSelectElement(e, false)}
          />

          <div className="drag-handler top"></div>
          <div className="drag-handler bottom"></div>
        </div>
      </div>
    </div>
  )
}

export default TextElement
