// src/views/components/element/TableElement/index.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react'
import { useMainStore, useSlidesStore } from '@/store'
import type { PPTTableElement, TableCell } from '@/types/slides'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'

import EditableTable from './EditableTable'
import './index.scss'
import type { ContextmenuItem } from '@/components/Contextmenu/types'
import useContextMenu from '@/hooks/useContextMenu'

export interface ElementProps {
  elementInfo: PPTTableElement;
  selectElement: (
    e: MouseEvent | TouchEvent,
    element: PPTTableElement,
    canMove?: boolean
  ) => void;
  contextmenus: () => ContextmenuItem[] | null;
}

const TableElement: React.FC<ElementProps> = ({
  elementInfo,
  selectElement,
  contextmenus,
}) => {
  const element = elementInfo as PPTTableElement
  const {
    canvasScale,
    handleElementId,
    isScaling,
    setDisableHotkeysState,
    setSelectedTableCells,
  } = useMainStore()
  const { updateElement } = useSlidesStore()
  const { addHistorySnapshot } = useHistorySnapshot()

  const elementRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)
  const [editable, setEditable] = useState(false)
  const realHeightCache = useRef(-1)

  const handleSelectElement = (
    e: React.MouseEvent | React.TouchEvent,
    canMove = true
  ) => {
    e.stopPropagation()
    selectElement?.(e.nativeEvent, element, canMove)
  }

  // Handle editable state change and hotkeys disabling
  useEffect(() => {
    if (handleElementId !== element.id) setEditable(false)
  }, [handleElementId, element.id])

  useEffect(() => {
    setDisableHotkeysState(editable)
  }, [editable, setDisableHotkeysState])

  const startEdit = () => {
    setEditable(true)
  }

  // Handle scaling and height updates
  useEffect(() => {
    if (handleElementId !== element.id) return

    if (isScaling) setEditable(false)

    if (!isScaling && realHeightCache.current !== -1) {
      updateElement({
        id: element.id,
        props: { height: realHeightCache.current },
      })
      realHeightCache.current = -1
    }
  }, [isScaling, handleElementId, element.id, updateElement])

  const updateTableElementHeight = useCallback(
    (entries: ResizeObserverEntry[]) => {
      const contentRect = entries[0].contentRect
      if (!elementRef.current) return

      const realHeight = contentRect.height

      if (element.height !== realHeight) {
        if (!isScaling) {
          updateElement({
            id: element.id,
            props: { height: realHeight },
          })
        }
        else realHeightCache.current = realHeight
      }
    },
    [element.height, element.id, isScaling, updateElement]
  )

  useEffect(() => {
    const resizeObserver = new ResizeObserver(updateTableElementHeight)
    if (elementRef.current) resizeObserver.observe(elementRef.current)
    return () => {
      if (elementRef.current) resizeObserver.unobserve(elementRef.current)
      resizeObserver.disconnect()
    }
  }, [updateTableElementHeight])

  const updateTableCells = (data: TableCell[][]) => {
    updateElement({
      id: element.id,
      props: { data },
    })
    addHistorySnapshot()
  }

  const updateColWidths = (widths: number[]) => {
    const width = widths.reduce((a, b) => a + b)
    const colWidths = widths.map((item) => item / width)

    updateElement({
      id: element.id,
      props: { width, colWidths },
    })
    addHistorySnapshot()
  }

  const updateSelectedCells = (cells: string[]) => {
    // We use setTimeout to avoid update loop if needed, but here it should be fine
    setTimeout(() => setSelectedTableCells(cells), 0)
  }

  /**
   * 绑定右键菜单到内容容器
   */
  useContextMenu(contentRef, () => contextmenus?.() || [])

  return (
    <div
      className="editable-element-table"
      ref={elementRef}
      style={{
        top: element.top + 'px',
        left: element.left + 'px',
        width: element.width + 'px',
      }}
    >
      <div
        className="rotate-wrapper"
        style={{ transform: `rotate(${element.rotate}deg)` }}
      >
        <div ref={contentRef} className="element-content">
          <EditableTable
            data={element.data}
            width={element.width}
            cellMinHeight={element.cellMinHeight}
            colWidths={element.colWidths}
            outline={element.outline}
            theme={element.theme}
            editable={editable}
            onChange={updateTableCells}
            onChangeColWidths={updateColWidths}
            onChangeSelectedCells={updateSelectedCells}
            onMouseDown={(e) => e.stopPropagation()}
          />
          {!editable && (
            <div
              className="table-mask"
              onDoubleClick={startEdit}
              onMouseDown={handleSelectElement}
              onTouchStart={handleSelectElement}
            >
              {handleElementId === element.id && (
                <div
                  className="mask-tip"
                  style={{ transform: `scale(${1 / canvasScale})` }}
                >
                  双击编辑
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default TableElement

// src/views/components/element/TableElement/index.vue
<template>
  <div 
    class="editable-element-table"
    ref="elementRef"
    :style="{
      top: elementInfo.top + 'px',
      left: elementInfo.left + 'px',
      width: elementInfo.width + 'px',
    }"
  >
    <div
      class="rotate-wrapper"
      :style="{ transform: `rotate(${elementInfo.rotate}deg)` }"
    >
      <div 
        class="element-content" 
        v-contextmenu="contextmenus"
      >
        <EditableTable 
          @mousedown.stop
          :data="elementInfo.data"
          :width="elementInfo.width"
          :cellMinHeight="elementInfo.cellMinHeight"
          :colWidths="elementInfo.colWidths"
          :outline="elementInfo.outline"
          :theme="elementInfo.theme"
          :editable="editable"
          @change="data => updateTableCells(data)"
          @changeColWidths="widths => updateColWidths(widths)"
          @changeSelectedCells="cells => updateSelectedCells(cells)"
        />
        <div 
          class="table-mask" 
          v-if="!editable"
          @dblclick="startEdit()"
          @mousedown="$event => handleSelectElement($event)"
          @touchstart="$event => handleSelectElement($event)"
        >
          <div class="mask-tip" v-if="handleElementId === elementInfo.id" :style="{ transform: `scale(${ 1 / canvasScale })` }">双击编辑</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { nextTick, onMounted, onUnmounted, ref, watch, useTemplateRef } from 'vue'
import { storeToRefs } from 'pinia'
import { useMainStore, useSlidesStore } from '@/store'
import type { PPTTableElement, TableCell } from '@/types/slides'
import type { ContextmenuItem } from '@/components/Contextmenu/types'
import useHistorySnapshot from '@/hooks/useHistorySnapshot'

import EditableTable from './EditableTable.vue'

const props = defineProps<{
  elementInfo: PPTTableElement
  selectElement: (e: MouseEvent | TouchEvent, element: PPTTableElement, canMove?: boolean) => void
  contextmenus: () => ContextmenuItem[] | null
}>()

const mainStore = useMainStore()
const slidesStore = useSlidesStore()
const { canvasScale, handleElementId, isScaling } = storeToRefs(mainStore)

const elementRef = useTemplateRef<HTMLElement>('elementRef')

const { addHistorySnapshot } = useHistorySnapshot()

/**
 * 处理元素选择事件
 * @param e 鼠标或触摸事件
 */
const handleSelectElement = (e: MouseEvent | TouchEvent) => {
  e.stopPropagation()

  props.selectElement(e, props.elementInfo)
}

// 更新表格的可编辑状态，表格处于编辑状态时需要禁用全局快捷键
const editable = ref(false)

watch(handleElementId, () => {
  if (handleElementId.value !== props.elementInfo.id) editable.value = false
})

watch(editable, () => {
  mainStore.setDisableHotkeysState(editable.value)
})

/**
 * 开始编辑表格
 */
const startEdit = () => {
  editable.value = true
}

// 监听表格元素的尺寸变化，当高度变化时，更新高度到vuex
// 如果高度变化时正处在缩放操作中，则等待缩放操作结束后再更新
const realHeightCache = ref(-1)

watch(isScaling, () => {
  if (handleElementId.value !== props.elementInfo.id) return

  if (isScaling.value) editable.value = false

  if (!isScaling.value && realHeightCache.value !== -1) {
    slidesStore.updateElement({
      id: props.elementInfo.id,
      props: { height: realHeightCache.value },
    })
    realHeightCache.value = -1
  }
})

const updateTableElementHeight = (entries: ResizeObserverEntry[]) => {
  const contentRect = entries[0].contentRect
  if (!elementRef.value) return

  const realHeight = contentRect.height

  if (props.elementInfo.height !== realHeight) {
    if (!isScaling.value) {
      slidesStore.updateElement({
        id: props.elementInfo.id,
        props: { height: realHeight },
      })
    }
    else realHeightCache.value = realHeight
  }
}

const resizeObserver = new ResizeObserver(updateTableElementHeight)

onMounted(() => {
  if (elementRef.value) resizeObserver.observe(elementRef.value)
})
onUnmounted(() => {
  if (elementRef.value) resizeObserver.unobserve(elementRef.value)
})

// 更新表格内容数据
const updateTableCells = (data: TableCell[][]) => {
  slidesStore.updateElement({
    id: props.elementInfo.id, 
    props: { data },
  })
  addHistorySnapshot()
}

// 更新表格的列宽数据
const updateColWidths = (widths: number[]) => {
  const width = widths.reduce((a, b) => a + b)
  const colWidths = widths.map(item => item / width)

  slidesStore.updateElement({
    id: props.elementInfo.id, 
    props: { width, colWidths },
  })
  addHistorySnapshot()
}

// 更新表格当前选中的单元格
const updateSelectedCells = (cells: string[]) => {
  nextTick(() => mainStore.setSelectedTableCells(cells))
}
</script>

<style lang="scss" scoped>
.editable-element-table {
  position: absolute;
}
.rotate-wrapper {
  width: 100%;
  height: 100%;
}
.element-content {
  width: 100%;
  height: 100%;
  position: relative;
  cursor: move;
}
.table-mask {
  @include absolute-0();

  opacity: 0;
  transition: opacity $transitionDelay;

  .mask-tip {
    position: absolute;
    top: 5px;
    left: 5px;
    background-color: rgba($color: #000, $alpha: .5);
    color: #fff;
    padding: 6px 12px;
    font-size: 12px;
    transform-origin: 0 0;
  }

  &:hover {
    opacity: .9;
  }
}
</style>
