// src/views/components/element/LatexElement/index.vue
<template>
  <div 
    class="editable-element-latex"
    :style="{
      top: elementInfo.top + 'px',
      left: elementInfo.left + 'px',
      width: elementInfo.width + 'px',
      height: elementInfo.height + 'px',
    }"
  >
    <div
      class="rotate-wrapper"
      :style="{ transform: `rotate(${elementInfo.rotate}deg)` }"
    >
      <div 
        class="element-content" 
        v-contextmenu="contextmenus"
        @mousedown="$event => handleSelectElement($event)"
        @touchstart="$event => handleSelectElement($event)"
        @dblclick="openLatexEditor()"
      >
        <svg 
          overflow="visible" 
          :width="elementInfo.width"
          :height="elementInfo.height"
          :stroke="elementInfo.color" 
          :stroke-width="elementInfo.strokeWidth" 
          fill="none" 
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <g 
            :transform="`scale(${elementInfo.width / elementInfo.viewBox[0]}, ${elementInfo.height / elementInfo.viewBox[1]}) translate(0,0) matrix(1,0,0,1,0,0)`"
          >
            <path :d="elementInfo.path"></path>
          </g>
        </svg>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { PPTLatexElement } from '@/types/slides'
import type { ContextmenuItem } from '@/components/Contextmenu/types'
import emitter, { EmitterEvents } from '@/utils/emitter'

const props = defineProps<{
  elementInfo: PPTLatexElement
  selectElement: (e: MouseEvent | TouchEvent, element: PPTLatexElement, canMove?: boolean) => void
  contextmenus: () => ContextmenuItem[] | null
}>()

/**
 * 处理元素选择事件
 * @param e 鼠标或触摸事件
 */
const handleSelectElement = (e: MouseEvent | TouchEvent) => {
  e.stopPropagation()

  props.selectElement(e, props.elementInfo)
}

const openLatexEditor = () => {
  emitter.emit(EmitterEvents.OPEN_LATEX_EDITOR)
}
</script>

<style lang="scss" scoped>
.editable-element-latex {
  position: absolute;
}
.rotate-wrapper {
  width: 100%;
  height: 100%;
}
.element-content {
  width: 100%;
  height: 100%;
  position: relative;
  cursor: move;

  svg {
    transform-origin: 0 0;
    overflow: visible;
  }
}
</style>

// src/views/components/element/LatexElement/index.tsx
import React from 'react'
import type { PPTLatexElement } from '@/types/slides'
import emitter, { EmitterEvents } from '@/utils/emitter'
import { ElementProps } from '../types'
import './index.scss'

const LatexElement: React.FC<ElementProps> = ({ elementInfo, selectElement, contextmenus }) => {
  const element = elementInfo as PPTLatexElement

  const handleSelectElement = (e: React.MouseEvent | React.TouchEvent) => {
    e.stopPropagation()
    selectElement?.(e, element)
  }

  const openLatexEditor = () => {
    emitter.emit(EmitterEvents.OPEN_LATEX_EDITOR)
  }

  return (
    <div 
      className="editable-element-latex"
      style={{
        top: element.top + 'px',
        left: element.left + 'px',
        width: element.width + 'px',
        height: element.height + 'px',
      }}
    >
      <div
        className="rotate-wrapper"
        style={{ transform: `rotate(${element.rotate}deg)` }}
      >
        <div 
          className="element-content" 
          // v-contextmenu="contextmenus"
          onMouseDown={handleSelectElement}
          onTouchStart={handleSelectElement}
          onDoubleClick={openLatexEditor}
        >
          <svg 
            overflow="visible" 
            width={element.width}
            height={element.height}
            stroke={element.color} 
            strokeWidth={element.strokeWidth} 
            fill="none" 
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <g 
              transform={`scale(${element.width / element.viewBox[0]}, ${element.height / element.viewBox[1]}) translate(0,0) matrix(1,0,0,1,0,0)`}
            >
              <path d={element.path}></path>
            </g>
          </svg>
        </div>
      </div>
    </div>
  )
}

export default LatexElement
