// src/views/components/ThumbnailSlide/ThumbnailElement.vue
<template>
  <div
    class="base-element"
    :class="`base-element-${elementInfo.id}`"
    :style="{
      zIndex: elementIndex,
    }"
  >
    <component
      :is="currentElementComponent"
      :elementInfo="elementInfo"
      target="thumbnail"
    ></component>
  </div>
</template>

<script lang="ts" setup>
import { computed } from 'vue'
import { ElementTypes, type PPTElement } from '@/types/slides'

import BaseImageElement from '@/views/components/element/ImageElement/BaseImageElement.vue'
import BaseTextElement from '@/views/components/element/TextElement/BaseTextElement.vue'
import BaseShapeElement from '@/views/components/element/ShapeElement/BaseShapeElement.vue'
import BaseLineElement from '@/views/components/element/LineElement/BaseLineElement.vue'
import BaseChartElement from '@/views/components/element/ChartElement/BaseChartElement.vue'
import BaseTableElement from '@/views/components/element/TableElement/BaseTableElement.vue'
import BaseLatexElement from '@/views/components/element/LatexElement/BaseLatexElement.vue'
import BaseVideoElement from '@/views/components/element/VideoElement/BaseVideoElement.vue'
import BaseAudioElement from '@/views/components/element/AudioElement/BaseAudioElement.vue'

const props = defineProps<{
  elementInfo: PPTElement;
  elementIndex: number;
}>()

const currentElementComponent = computed<unknown>(() => {
  const elementTypeMap = {
    [ElementTypes.IMAGE]: BaseImageElement,
    [ElementTypes.TEXT]: BaseTextElement,
    [ElementTypes.SHAPE]: BaseShapeElement,
    [ElementTypes.LINE]: BaseLineElement,
    [ElementTypes.CHART]: BaseChartElement,
    [ElementTypes.TABLE]: BaseTableElement,
    [ElementTypes.LATEX]: BaseLatexElement,
    [ElementTypes.VIDEO]: BaseVideoElement,
    [ElementTypes.AUDIO]: BaseAudioElement,
  }
  return elementTypeMap[props.elementInfo.type] || null
})
</script>

// src/views/components/ThumbnailSlide/ThumbnailElement.tsx
import React, { useMemo } from 'react'
import { ElementTypes, type PPTElement } from '@/types/slides'

import clsx from 'clsx'
import BaseImageElement from '../element/ImageElement/BaseImageElement'
import BaseTextElement from '../element/TextElement/BaseTextElement'
import BaseShapeElement from '../element/ShapeElement/BaseShapeElement'
import BaseLineElement from '../element/LineElement/BaseLineElement'
import BaseChartElement from '../element/ChartElement/BaseChartElement'
import BaseTableElement from '../element/TableElement/BaseTableElement'
import BaseLatexElement from '../element/LatexElement/BaseLatexElement'
import BaseVideoElement from '../element/VideoElement/BaseVideoElement'
import BaseAudioElement from '../element/AudioElement/BaseAudioElement'

interface ThumbnailElementProps {
  elementInfo: PPTElement;
  elementIndex: number;
}

const ThumbnailElement: React.FC<ThumbnailElementProps> = ({
  elementInfo,
  elementIndex,
}) => {
  const CurrentElementComponent = useMemo(() => {
    const elementTypeMap = {
      [ElementTypes.IMAGE]: BaseImageElement,
      [ElementTypes.TEXT]: BaseTextElement,
      [ElementTypes.SHAPE]: BaseShapeElement,
      [ElementTypes.LINE]: BaseLineElement,
      [ElementTypes.CHART]: BaseChartElement,
      [ElementTypes.TABLE]: BaseTableElement,
      [ElementTypes.LATEX]: BaseLatexElement,
      [ElementTypes.VIDEO]: BaseVideoElement,
      [ElementTypes.AUDIO]: BaseAudioElement,
    }
    return elementTypeMap[elementInfo.type] || null
  }, [elementInfo.type])

  return (
    <div
      className={clsx('thumbnail-element', `base-element-${elementInfo.id}`)}
      style={{
        zIndex: elementIndex,
      }}
    >
      {/* @ts-ignore */}
      <CurrentElementComponent elementInfo={elementInfo} />
    </div>
  )
}

export default ThumbnailElement
