// src/views/components/element/LineElement/index.vue
<template>
  <div 
    class="editable-element-shape"
    :style="{
      top: elementInfo.top + 'px',
      left: elementInfo.left + 'px',
    }"
  >
    <div 
      class="element-content" 
      :style="{ filter: shadowStyle ? `drop-shadow(${shadowStyle})` : '' }"
      @mousedown="$event => handleSelectElement($event)"
      @touchstart="$event => handleSelectElement($event)"
    >
      <svg
        overflow="visible" 
        :width="svgWidth"
        :height="svgHeight"
      >
        <defs>
          <LinePointMarker
            v-if="elementInfo.points[0]"
            :id="elementInfo.id"
            position="start"
            :type="elementInfo.points[0]"
            :color="elementInfo.color"
            :baseSize="elementInfo.width"
          />
          <LinePointMarker
            v-if="elementInfo.points[1]"
            :id="elementInfo.id"
            position="end"
            :type="elementInfo.points[1]"
            :color="elementInfo.color"
            :baseSize="elementInfo.width"
          />
        </defs>
				<path
          class="line-point"
          :d="path" 
          :stroke="elementInfo.color" 
          :stroke-width="elementInfo.width" 
          :stroke-dasharray="lineDashArray"
          fill="none" 
          :marker-start="elementInfo.points[0] ? `url(#${elementInfo.id}-${elementInfo.points[0]}-start)` : ''"
          :marker-end="elementInfo.points[1] ? `url(#${elementInfo.id}-${elementInfo.points[1]}-end)` : ''"
        ></path>
				<path
          class="line-path"
          :d="path" 
          stroke="transparent" 
          stroke-width="20" 
          fill="none" 
          v-contextmenu="contextmenus"
        ></path>
			</svg>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed } from 'vue'
import type { PPTLineElement } from '@/types/slides'
import { getLineElementPath } from '@/utils/element'
import type { ContextmenuItem } from '@/components/Contextmenu/types'
import useElementShadow from '@/views/components/element/hooks/useElementShadow'

import LinePointMarker from './LinePointMarker.vue'

const props = defineProps<{
  elementInfo: PPTLineElement
  selectElement: (e: MouseEvent | TouchEvent, element: PPTLineElement, canMove?: boolean) => void
  contextmenus: () => ContextmenuItem[] | null
}>()

/**
 * 处理元素选择事件
 * @param e 鼠标或触摸事件
 */
const handleSelectElement = (e: MouseEvent | TouchEvent) => {
  e.stopPropagation()

  props.selectElement(e, props.elementInfo)
}

const shadow = computed(() => props.elementInfo.shadow)
const { shadowStyle } = useElementShadow(shadow)

const svgWidth = computed(() => {
  const width = Math.abs(props.elementInfo.start[0] - props.elementInfo.end[0])
  return width < 24 ? 24 : width
})
const svgHeight = computed(() => {
  const height = Math.abs(props.elementInfo.start[1] - props.elementInfo.end[1])
  return height < 24 ? 24 : height
})

const lineDashArray = computed(() => {
  const size = props.elementInfo.width
  if (props.elementInfo.style === 'dashed') return size <= 8 ? `${size * 5} ${size * 2.5}` : `${size * 5} ${size * 1.5}`
  if (props.elementInfo.style === 'dotted') return size <= 8 ? `${size * 1.8} ${size * 1.6}` : `${size * 1.5} ${size * 1.2}`
  return '0 0'
})

const path = computed(() => {
  return getLineElementPath(props.elementInfo)
})
</script>

<style lang="scss" scoped>
.editable-element-shape {
  position: absolute;
  pointer-events: none;
}

.element-content {
  width: 100%;
  height: 100%;
  position: relative;

  svg {
    transform-origin: 0 0;
    overflow: visible;
  }
}
.line-path, .line-point {
  pointer-events: all;
  cursor: move;
}
</style>

// src/views/components/element/LineElement/index.tsx
import React, { useMemo } from 'react'
import type { PPTLineElement, LinePoint } from '@/types/slides'
import { getLineElementPath } from '@/utils/element'
import useElementShadow from '@/views/components/element/hooks/useElementShadow'

import LinePointMarker from './LinePointMarker'
import { ElementProps } from '../types'
import './index.scss'

const LineElement: React.FC<ElementProps> = ({ elementInfo, selectElement, contextmenus }) => {
  const element = elementInfo as PPTLineElement
  const { shadowStyle } = useElementShadow(element.shadow)

  const handleSelectElement = (e: React.MouseEvent | React.TouchEvent) => {
    e.stopPropagation()
    selectElement?.(e, element)
  }

  const svgWidth = useMemo(() => {
    const width = Math.abs(element.start[0] - element.end[0])
    return width < 24 ? 24 : width
  }, [element.start, element.end])

  const svgHeight = useMemo(() => {
    const height = Math.abs(element.start[1] - element.end[1])
    return height < 24 ? 24 : height
  }, [element.start, element.end])

  const lineDashArray = useMemo(() => {
    const size = element.width
    if (element.style === 'dashed') return size <= 8 ? `${size * 5} ${size * 2.5}` : `${size * 5} ${size * 1.5}`
    if (element.style === 'dotted') return size <= 8 ? `${size * 1.8} ${size * 1.6}` : `${size * 1.5} ${size * 1.2}`
    return '0 0'
  }, [element.width, element.style])

  const path = useMemo(() => {
    return getLineElementPath(element)
  }, [element])

  const startPoint = element.points[0] as Exclude<LinePoint, ''> | undefined
  const endPoint = element.points[1] as Exclude<LinePoint, ''> | undefined

  return (
    <div 
      className="editable-element-shape"
      style={{
        top: element.top + 'px',
        left: element.left + 'px',
        width: svgWidth + 'px',
        height: svgHeight + 'px',
      }}
    >
      <div 
        className="element-content" 
        style={{ filter: shadowStyle ? `drop-shadow(${shadowStyle})` : '' }}
        onMouseDown={handleSelectElement}
        onTouchStart={handleSelectElement}
      >
        <svg
          overflow="visible" 
          width={svgWidth}
          height={svgHeight}
        >
          <defs>
            {startPoint && (
              <LinePointMarker
                id={element.id}
                position="start"
                type={startPoint}
                color={element.color}
                baseSize={element.width}
              />
            )}
            {endPoint && (
              <LinePointMarker
                id={element.id}
                position="end"
                type={endPoint}
                color={element.color}
                baseSize={element.width}
              />
            )}
          </defs>
          <path
            className="line-point"
            d={path} 
            stroke={element.color} 
            strokeWidth={element.width} 
            strokeDasharray={lineDashArray}
            fill="none" 
            markerStart={startPoint ? `url(#${element.id}-${startPoint}-start)` : ''}
            markerEnd={endPoint ? `url(#${element.id}-${endPoint}-end)` : ''}
          ></path>
          <path
            className="line-path"
            d={path} 
            stroke="transparent" 
            strokeWidth="20" 
            fill="none" 
            // v-contextmenu="contextmenus"
          ></path>
        </svg>
      </div>
    </div>
  )
}

export default LineElement
